"""add anomaly fields to transactions

Revision ID: 94ad26d200c3
Revises: 43fd7d7e5fb7
Create Date: 2026-09-20 18:16:49.900936

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94ad26d200c3'
down_revision: Union[str, None] = '43fd7d7e5fb7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('is_anomaly', sa.Boolean(), nullable=True))
    op.add_column('transactions', sa.Column('anomaly_score', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'anomaly_score')
    op.drop_column('transactions', 'is_anomaly')
    # ### end Alembic commands ###
